[server]
host = "http://localhost"
port = 8545

[blockchain]
account = "0x02d31960D48ef135328f85cE73e22e1e9537a20E"
password = "password"

[votes]
name = "System_Votes"
address = "address_contracts"